### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by xiaoxiangmoe** [xiaoxiangmoe/typescript-macros#1]
- [x] basic example of macros
- [x] example of converting type to runtime value
- [x] tslint + prettier
- [x] support babel-plugin-macros and typescript-macros in a single package(see:  https://github.com/kentcdodds/babel-plugin-macros/issues/94#issuecomment-446282328 )
- [ ] support macros which is '.ts' file (require ts file and compile it in memory,for example: `import foo from '../../utils/foo.tsmacro'`)
- [ ] TypeScript language service plugin for tsmacros
- [x] document
- [ ] adapt ts-loader https://github.com/TypeStrong/ts-loader/issues/860
- [ ] unit test (waiting for this issue:  https://github.com/kulshekhar/ts-jest/issues/899 )
- [ ] ci (wating for unit test)
- [ ] cd (wating for [github actions](https://github.com/features/actions) for public repos)

-----

Maybe it allow users to define macros in non-macro file(such as `util/a.ts` ) in the future.
